import {readFile,writeFile} from 'node:fs/promises';
import {load} from 'cheerio';
const inventory=JSON.parse(await readFile('audit/public-inventory.json','utf8')) as {url:string;file:string;bytes:number}[];
const rows=await Promise.all(inventory.map(async page=>{
 const html=await readFile('audit/'+page.file,'utf8');const $=load(html);
 const scripts=$('script[src]').toArray().map(el=>new URL($(el).attr('src')!,page.url).href);
 const images=$('img').toArray();
 return {url:page.url,htmlBytes:Buffer.byteLength(html),title:$('title').text(),description:$('meta[name="description"]').attr('content')??'',canonical:$('link[rel="canonical"]').attr('href')??'',h1:$('h1').toArray().map(el=>$(el).text().trim()),scripts,externalScriptHosts:[...new Set(scripts.map(s=>new URL(s).hostname).filter(host=>host!=='femprobiotics.co'))],inlineScriptBytes:$('script:not([src])').toArray().reduce((sum,el)=>sum+Buffer.byteLength($(el).html()??''),0),images:{total:images.length,missingAlt:images.filter(el=>$(el).attr('alt')===undefined).length,missingDimensions:images.filter(el=>!$(el).attr('width')||!$(el).attr('height')).length,lazy:images.filter(el=>$(el).attr('loading')==='lazy').length,responsive:images.filter(el=>Boolean($(el).attr('srcset'))).length},structuredData:$('script[type="application/ld+json"]').length};
}));
await writeFile('audit/page-quality.json',JSON.stringify(rows,null,2));
const hosts=new Map<string,number>();for(const row of rows)for(const host of row.externalScriptHosts)hosts.set(host,(hosts.get(host)??0)+1);
const md=['# SEO, imágenes y scripts — línea base','','Mediciones estáticas del HTML capturado. No son métricas Lighthouse ni Core Web Vitals. Los conteos incluyen elementos ocultos, plantillas y recursos administrados por aplicaciones.','','## Proveedores externos detectados','','| Host | Páginas |','|---|---|',...[...hosts].sort((a,b)=>b[1]-a[1]).map(([host,count])=>`| ${host} | ${count} |`),'','## Por ruta','','| Ruta | HTML KB | Scripts | Imágenes | Sin dimensiones | Sin alt | H1 | JSON-LD |','|---|---:|---:|---:|---:|---:|---:|---:|',...rows.map(r=>`| ${new URL(r.url).pathname} | ${Math.round(r.htmlBytes/1024)} | ${r.scripts.length} | ${r.images.total} | ${r.images.missingDimensions} | ${r.images.missingAlt} | ${r.h1.length} | ${r.structuredData} |`),'','## Criterios de intervención','','Mantener pagos, reseñas y marketing hasta verificar su función. Cargar scripts de componentes solo cuando sus elementos existan. Conservar el contenido SEO administrado por Shopify y revisar las páginas sin H1 o con múltiples H1 antes de cambiar jerarquías. Añadir dimensiones reales a imágenes y preservar srcset. Medir rendimiento después en el preview nativo con las mismas condiciones de red/dispositivo.'];
await writeFile('docs/QUALITY.md',md.join('\n')+'\n');
console.log(`${rows.length} páginas analizadas; ${hosts.size} hosts externos inventariados.`);
